/*
* generated by Xtext
*/
package nl.dslmeinte.xtext.less.ui.contentassist;

import nl.dslmeinte.xtext.less.ui.contentassist.AbstractLessProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class LessProposalProvider extends AbstractLessProposalProvider {

}
