/*
 * generated by Xtext
 */
package nl.dslmeinte.xtext.less.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LessUiModule extends nl.dslmeinte.xtext.less.ui.AbstractLessUiModule {
	public LessUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
