/*
 * generated by Xtext
 */
package nl.dslmeinte.xtext.css;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CSSRuntimeModule extends nl.dslmeinte.xtext.css.AbstractCSSRuntimeModule {

}
