/*
 * generated by Xtext
 */
package nl.dslmeinte.xtext.css.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CSSUiModule extends nl.dslmeinte.xtext.css.ui.AbstractCSSUiModule {
	public CSSUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
