/*
* generated by Xtext
*/
package nl.dslmeinte.xtext.css.ui.contentassist;

import nl.dslmeinte.xtext.css.ui.contentassist.AbstractCSSProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class CSSProposalProvider extends AbstractCSSProposalProvider {

}
