/*
* generated by Xtext
*/
package nl.dslmeinte.xtext.css.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class CSSOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
